# Generated by Django 3.2.4 on 2021-09-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_x', models.PositiveIntegerField(default=0)),
                ('size_y', models.PositiveIntegerField(default=0)),
                ('shape', models.CharField(choices=[('e', 'Elliptical'), ('s', 'Spiral'), ('i', 'Irregular')], default='s', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='quickstart.galaxy')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.FloatField(default=0)),
                ('age_in_centuries', models.FloatField(default=0)),
                ('mass_in_suns', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('bd', 'Brown Dwarf'), ('rd', 'Red Dwarf'), ('yd', 'Yellow Dwarf'), ('rg', 'Red Giant'), ('bg', 'Blue Giant'), ('sg', 'Supergiant'), ('wd', 'White Dwarf'), ('ns', 'Neutron Star'), ('p', 'Pulsar'), ('bh', 'Black Hole'), ('o', 'other')], default='yd', max_length=10)),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.starsystem')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.FloatField(default=0)),
                ('age_in_centuries', models.FloatField(default=0)),
                ('mass_in_suns', models.FloatField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('atmosphere', models.CharField(max_length=100)),
                ('habitable', models.BooleanField(default=False)),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.starsystem')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.FloatField(default=0)),
                ('age_in_centuries', models.FloatField(default=0)),
                ('mass_in_suns', models.FloatField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('atmosphere', models.CharField(max_length=100)),
                ('habitable', models.BooleanField(default=False)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.planet')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
