# Generated by Django 3.2.4 on 2021-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='type',
            new_name='star_type',
        ),
        migrations.AlterField(
            model_name='planet',
            name='atmosphere',
            field=models.CharField(default='No atmosphere', max_length=100),
        ),
    ]
