# Generated by Django 3.2.4 on 2021-07-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210624_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcolor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='carcolor',
            name='name',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default='green', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carcolor'),
        ),
    ]
