# Generated by Django 3.2.4 on 2021-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210709_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='white', max_length=100, verbose_name='CarColor'),
        ),
    ]
