# Generated by Django 3.2.4 on 2021-07-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default='white', null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carcolor'),
        ),
    ]
